# Generated by Django 3.2.11 on 2022-01-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptop',
            table='laptops',
        ),
    ]
